images:
  runs-on-gpu-pinned:
    platform: "linux"
    arch: "x64"
    owner: "135269210855" # runs-on
    # to find, go to 
    # https://us-east-2.console.aws.amazon.com/ec2/home?region=us-east-2#Images:visibility=public-images;search=:runs-on;v=3;$case=tags:false%5C,client:false;$regex=tags:false%5C,client:false
    name: "runs-on-v2.2-ubuntu22-gpu-x64-20250220122045"

  runs-on-cpu-pinned:
    platform: "linux"
    arch: "x64"
    owner: "135269210855" # runs-on
    name: "runs-on-v2.2-ubuntu22-full-x64-20250220122045"

  custom-image-2025-04-18:
    platform: "linux"
    arch: "x64"
    ami: "ami-0c38c1bd40602cb52"
