images:
  dlami-x64:
    platform: "linux"
    arch: "x64"
    owner: "898082745236" # AWS
    name: "Amazon Linux 2 AMI with NVIDIA TESLA GPU Driver*"

runners:
  gpu-nvidia:
    family: ["g4dn.xlarge"]
    image: dlami-x64
