images:
  amazon-linux-gpu-x64:
    platform: "linux"
    arch: "x64"
    owner: "898082745236" # AWS
    name: "Amazon Linux 2 AMI with NVIDIA TESLA GPU Driver*"

  dlami-x64:
    platform: "linux"
    arch: "x64"
    owner: "898082745236" # AWS
    name: "Deep Learning Base OSS Nvidia Driver GPU AMI (Ubuntu 22.04)*"

runners:
  gpu-nvidia:
    family: ["g4dn.xlarge"]
    image: amazon-linux-gpu-x64
