images:
  runs-on-gpu-pinned:
    platform: "linux"
    arch: "x64"
    owner: "135269210855" # runs-on
    name: "runs-on-v2.2-ubuntu22-gpu-x64-20250123194414"

  runs-on-cpu-pinned:
    platform: "linux"
    arch: "x64"
    owner: "135269210855" # runs-on
    name: "runs-on-v2.2-ubuntu22-full-x64-20250101080516"
