#ifndef _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_SYMBOLIC_CG_OP_ATTRS_AND_TRAINING_SIGNATURE_WITH_SHAPES_H
#define _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_SYMBOLIC_CG_OP_ATTRS_AND_TRAINING_SIGNATURE_WITH_SHAPES_H

#include "task-spec/symbolic_cg_op_attrs_and_training_signature_with_shapes.dtg.h"
#include "task-spec/symbolic_layer_training_tensor_group_signature_with_shapes.dtg.h"

namespace FlexFlow {

SymbolicLayerTrainingTensorGroupSignatureWithShapes
  get_signature_with_shapes(SymbolicCgOpAttrsAndTrainingSignatureWithShapes const &);

SymbolicCgOpAttrsAndTrainingSignatureWithShapes
  make_symbolic_cg_op_attrs_and_signature_with_shapes(
    ComputationGraphOpAttrs const &,
    SymbolicLayerTrainingTensorGroupSignatureWithShapes const &);

} // namespace FlexFlow

#endif
