#ifndef _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_TRAINING_LAYER_SYMBOLIC_TENSOR_GROUP_SIGNATURE_WITH_SHAPES_H
#define _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_TRAINING_LAYER_SYMBOLIC_TENSOR_GROUP_SIGNATURE_WITH_SHAPES_H

#include "task-spec/symbolic_layer_tensor_shape_signature.dtg.h"
#include "task-spec/training_layer_symbolic_tensor_group_signature_with_shapes.dtg.h"
#include "task-spec/training_layer_symbolic_tensor_group_signature.dtg.h"

namespace FlexFlow {

TrainingLayerSymbolicTensorGroupSignature
  drop_shapes_from_signature(TrainingLayerSymbolicTensorGroupSignatureWithShapes const &);

SymbolicLayerTensorShapeSignature
  get_shape_signature(TrainingLayerSymbolicTensorGroupSignatureWithShapes const &);

} // namespace FlexFlow

#endif
